/**
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership.
 *
 * Camunda licenses this file to you under the MIT; you may not use this file
 * except in compliance with the MIT License.
 */

export const ELEMENT_DESCRIPTIONS = {
  'task': 'An unspecified step, often used as a placeholder',
  'user-task': 'Work that needs to be done by a person',
  'service-task': 'Automated work carried out by a job worker or connector',
  'send-task': 'Publishes a message to a receiver',
  'receive-task': 'Waits for a message to be received',
  'manual-task': 'A task done by a person without any tooling or UI',
  'rule-task': 'Evaluates a business rule, typically a DMN decision',
  'script-task': 'Runs a script',
  'call-activity': 'Calls another process as a reusable subprocess',
  'transaction': 'A subprocess that completes as a whole, or is compensated',
  'event-subprocess': 'A subprocess triggered by an event in its scope',
  'collapsed-subprocess': 'Groups elements into a subprocess, shown collapsed',
  'expanded-subprocess': 'Groups elements into a subprocess, shown inline',
  'collapsed-ad-hoc-subprocess': 'Activities run in any order; shown collapsed',
  'expanded-ad-hoc-subprocess': 'Activities run in any order, any number of times',
  'exclusive-gateway': 'Routes the token down one path, based on data',
  'parallel-gateway': 'Splits the flow into parallel paths, or joins them',
  'inclusive-gateway': 'Takes every outgoing path whose condition is met',
  'complex-gateway': 'Models complex branching or merging behavior',
  'event-based-gateway': 'Follows the path of whichever event occurs first',
  'data-store-reference': 'Data that persists beyond the process instance',
  'data-object-reference': 'Data created and used within a process instance',
  'expanded-pool': 'A participant with its process shown inside',
  'collapsed-pool': 'A participant shown as a black box',
  'none-start-event': 'Where the process begins',
  'none-intermediate-throwing': 'Marks a point in the flow',
  'none-boundary-event': 'Handles an event that occurs while an activity is active',
  'none-end-event': 'Ends the current path',
  'message-start': 'Starts the process when a message is received',
  'timer-start': 'Starts the process on a defined timer',
  'conditional-start': 'Starts the process when a condition is met',
  'signal-start': 'Starts the process when a matching signal is broadcast',
  'error-start': 'Starts an event subprocess when an error is thrown',
  'escalation-start': 'Starts an event subprocess on an escalation',
  'compensation-start': 'Starts an event subprocess to handle compensation',
  'non-interrupting-message-start': 'Starts an event subprocess on a message, without interrupting',
  'non-interrupting-timer-start': 'Starts an event subprocess on a timer, without interrupting',
  'non-interrupting-conditional-start': 'Starts an event subprocess when a condition is met, without interrupting',
  'non-interrupting-signal-start': 'Starts an event subprocess on a signal, without interrupting',
  'non-interrupting-escalation-start': 'Starts an event subprocess on an escalation, without interrupting',
  'message-intermediate-catch': 'Waits until a message is received',
  'message-intermediate-throw': 'Sends a message',
  'timer-intermediate-catch': 'Waits for a defined time or duration',
  'escalation-intermediate-throw': 'Raises an escalation to a higher scope',
  'conditional-intermediate-catch': 'Waits until a condition is met',
  'link-intermediate-catch': 'Continues from a matching link event',
  'link-intermediate-throw': 'Jumps to a matching link event',
  'compensation-intermediate-throw': 'Triggers compensation of completed activities',
  'signal-intermediate-catch': 'Waits for a matching signal to be broadcast',
  'signal-intermediate-throw': 'Broadcasts a signal',
  'message-boundary': 'Interrupts the activity when a message is received',
  'timer-boundary': 'Interrupts the activity on a defined timer',
  'escalation-boundary': 'Interrupts the activity on an escalation',
  'conditional-boundary': 'Interrupts the activity when a condition is met',
  'error-boundary': 'Interrupts the activity when it throws an error',
  'cancel-boundary': 'Reacts when a transaction is canceled',
  'signal-boundary': 'Interrupts the activity on a matching signal',
  'compensation-boundary': 'Attaches a compensation handler to the activity',
  'non-interrupting-message-boundary': 'Reacts to a message while the activity continues',
  'non-interrupting-timer-boundary': 'Fires on a timer while the activity continues',
  'non-interrupting-escalation-boundary': 'Reacts to an escalation while the activity continues',
  'non-interrupting-conditional-boundary': 'Reacts when a condition is met; activity continues',
  'non-interrupting-signal-boundary': 'Reacts to a signal while the activity continues',
  'message-end': 'Ends the path and sends a message',
  'escalation-end': 'Ends the path and raises an escalation',
  'error-end': 'Ends the path by throwing an error',
  'cancel-end': 'Cancels the transaction and ends the path',
  'compensation-end': 'Ends the path and triggers compensation',
  'signal-end': 'Ends the path and broadcasts a signal',
  'terminate-end': 'Immediately ends all active paths in the scope',

  // sequence flows
  'sequence-flow': 'Connects one element to the next in the flow',
  'default-flow': 'The default path, taken when no other path condition is met',
  'conditional-flow': 'Taken only when its condition is met'
};
